[config]
schemaVersion = "0.0.1"


[package]
versionNumber = "1.1.2"
namespace = "Avocados"
name = "Tierless"
description = "Coming soon!.."
websiteUrl = "https://github.com/Chubrel/Tierless"
containsNsfwContent = false

[package.dependencies]


[build]
icon = "./icon.png"
readme = "./README.md"
changelog = "./CHANGELOG.md"
outdir = "./build"

[[build.copy]]
source = "./Tierless/bin/Debug/netstandard2.1"
dest = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "repo", ]

[publish.categories]
riskofrain2 = [ "client-side", "server-side", ]
